ERROR:__main__:Errored: 1 retry happened in running tx: DeliveryTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1635671858.268187000,0 too old; wrote at 1635671859.176552000,1: "sql txn" meta={id=658d1ecd pri=0.00341106 epo=0 ts=1635671859.176552000,1 min=1635671858.268187000,0 seq=48} lock=true stat=PENDING rts=1635671858.268187000,0 wto=false gul=1635671858.768187000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 74, in execute_tx
    each_tx_time = tx_ins.delivery_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 268, in delivery_transaction
    cur.execute(query)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: WriteTooOldError: write at timestamp 1635671858.268187000,0 too old; wrote at 1635671859.176552000,1: "sql txn" meta={id=658d1ecd pri=0.00341106 epo=0 ts=1635671859.176552000,1 min=1635671858.268187000,0 seq=48} lock=true stat=PENDING rts=1635671858.268187000,0 wto=false gul=1635671858.768187000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html

 ]
INFO:__main__:Running Tx DeliveryTxParams successful at the 2 time retry
ERROR:__main__:Errored: 1 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635671935.615791000,0 encountered previous write with future timestamp 1635671935.616361000,0 within uncertainty interval `t <= (local=1635671935.622580000,1, global=1635671936.115791000,0)`; observed timestamps: [{1 1635671935.616942000,0} {2 1635671935.622580000,1} {4 1635671935.615791000,0}]: "sql txn" meta={id=dac105ce pri=0.03097351 epo=0 ts=1635671935.615791000,0 min=1635671935.615791000,0 seq=0} lock=false stat=PENDING rts=1635671935.615791000,0 wto=false gul=1635671936.115791000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 84, in execute_tx
    each_tx_time = tx_ins.related_customer_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 555, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635671935.615791000,0 encountered previous write with future timestamp 1635671935.616361000,0 within uncertainty interval `t <= (local=1635671935.622580000,1, global=1635671936.115791000,0)`; observed timestamps: [{1 1635671935.616942000,0} {2 1635671935.622580000,1} {4 1635671935.615791000,0}]: "sql txn" meta={id=dac105ce pri=0.03097351 epo=0 ts=1635671935.615791000,0 min=1635671935.615791000,0 seq=0} lock=false stat=PENDING rts=1635671935.615791000,0 wto=false gul=1635671936.115791000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
INFO:__main__:Running Tx RelCustomerTxParams successful at the 2 time retry
ERROR:__main__:Errored: 1 retry happened in running tx: DeliveryTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_ABORT_SPAN): "sql txn" meta={id=1e619258 key=/Table/57/2/10/1 pri=0.04391023 epo=0 ts=1635672008.955550000,2 min=1635672006.764908000,0 seq=16} lock=true stat=ABORTED rts=1635672006.764908000,0 wto=false gul=1635672007.264908000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_abort_span
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 74, in execute_tx
    each_tx_time = tx_ins.delivery_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 268, in delivery_transaction
    cur.execute(query)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_ABORT_SPAN): "sql txn" meta={id=1e619258 key=/Table/57/2/10/1 pri=0.04391023 epo=0 ts=1635672008.955550000,2 min=1635672006.764908000,0 seq=16} lock=true stat=ABORTED rts=1635672006.764908000,0 wto=false gul=1635672007.264908000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_abort_span

 ]
INFO:__main__:Running Tx DeliveryTxParams successful at the 2 time retry
ERROR:__main__:Errored: 1 retry happened in running tx: DeliveryTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_ABORTED_RECORD_FOUND): "sql txn" meta={id=59ee812e key=/Table/57/2/10/1 pri=0.02435427 epo=0 ts=1635672049.092953000,2 min=1635672044.930375000,0 seq=196} lock=true stat=PENDING rts=1635672049.092953000,2 wto=false gul=1635672045.430375000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_aborted_record_found
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 74, in execute_tx
    each_tx_time = tx_ins.delivery_transaction(m_conn, m_params)
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 289, in delivery_transaction
    m_conn.commit()
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: TransactionAbortedError(ABORT_REASON_ABORTED_RECORD_FOUND): "sql txn" meta={id=59ee812e key=/Table/57/2/10/1 pri=0.02435427 epo=0 ts=1635672049.092953000,2 min=1635672044.930375000,0 seq=196} lock=true stat=PENDING rts=1635672049.092953000,2 wto=false gul=1635672045.430375000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_aborted_record_found

 ]
INFO:__main__:Running Tx DeliveryTxParams successful at the 2 time retry
INFO:__main__:============================ record when total_tx_num reaches 100=====================
