INFO:__main__:============================ record when total_tx_num reaches 100=====================
ERROR:__main__:Errored: 1 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635679080.433823000,0 encountered previous write with future timestamp 1635679080.433823000,1 within uncertainty interval `t <= (local=1635679080.442049000,0, global=1635679080.933823000,0)`; observed timestamps: [{1 1635679080.437557000,0} {4 1635679080.433823000,0} {5 1635679080.442049000,0}]: "sql txn" meta={id=578dc5c1 pri=0.02437402 epo=0 ts=1635679080.433823000,0 min=1635679080.433823000,0 seq=0} lock=false stat=PENDING rts=1635679080.433823000,0 wto=false gul=1635679080.933823000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 64, in run_tx
    each_tx_time = operation(m_conn)
  File "cockroachDB_driver.py", line 142, in <lambda>
    lambda l_conn: m_tx_ins.related_customer_transaction(l_conn, m_params))
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 551, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635679080.433823000,0 encountered previous write with future timestamp 1635679080.433823000,1 within uncertainty interval `t <= (local=1635679080.442049000,0, global=1635679080.933823000,0)`; observed timestamps: [{1 1635679080.437557000,0} {4 1635679080.433823000,0} {5 1635679080.442049000,0}]: "sql txn" meta={id=578dc5c1 pri=0.02437402 epo=0 ts=1635679080.433823000,0 min=1635679080.433823000,0 seq=0} lock=false stat=PENDING rts=1635679080.433823000,0 wto=false gul=1635679080.933823000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
ERROR:__main__:Errored: 2 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635679088.060683000,0 encountered previous write with future timestamp 1635679088.060683000,1 within uncertainty interval `t <= (local=1635679088.065481000,0, global=1635679088.560683000,0)`; observed timestamps: [{1 1635679088.061754000,0} {4 1635679088.060683000,0} {5 1635679088.065481000,0}]: "sql txn" meta={id=ba579d0d pri=0.01387335 epo=0 ts=1635679088.060683000,0 min=1635679088.060683000,0 seq=0} lock=false stat=PENDING rts=1635679088.060683000,0 wto=false gul=1635679088.560683000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 64, in run_tx
    each_tx_time = operation(m_conn)
  File "cockroachDB_driver.py", line 142, in <lambda>
    lambda l_conn: m_tx_ins.related_customer_transaction(l_conn, m_params))
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 551, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635679088.060683000,0 encountered previous write with future timestamp 1635679088.060683000,1 within uncertainty interval `t <= (local=1635679088.065481000,0, global=1635679088.560683000,0)`; observed timestamps: [{1 1635679088.061754000,0} {4 1635679088.060683000,0} {5 1635679088.065481000,0}]: "sql txn" meta={id=ba579d0d pri=0.01387335 epo=0 ts=1635679088.060683000,0 min=1635679088.060683000,0 seq=0} lock=false stat=PENDING rts=1635679088.060683000,0 wto=false gul=1635679088.560683000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
INFO:__main__:Running Tx RelCustomerTxParams successful at the 3 time retry
INFO:__main__:============================ record when total_tx_num reaches 200=====================
ERROR:__main__:Errored: 1 retry happened in running tx: RelCustomerTxParams, ErrorMsg: 
[ restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635679282.569042000,0 encountered previous write with future timestamp 1635679282.569042000,1 within uncertainty interval `t <= (local=1635679282.599620000,0, global=1635679283.069042000,0)`; observed timestamps: [{1 1635679282.570298000,0} {4 1635679282.569042000,0} {5 1635679282.599620000,0}]: "sql txn" meta={id=41ae8e17 pri=0.07121237 epo=0 ts=1635679282.569042000,0 min=1635679282.569042000,0 seq=0} lock=false stat=PENDING rts=1635679282.569042000,0 wto=false gul=1635679283.069042000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval
 ], Traceback: 
[ Traceback (most recent call last):
  File "cockroachDB_driver.py", line 64, in run_tx
    each_tx_time = operation(m_conn)
  File "cockroachDB_driver.py", line 142, in <lambda>
    lambda l_conn: m_tx_ins.related_customer_transaction(l_conn, m_params))
  File "/Users/nailixing/Documents/NUS_Modules/CS5424_Distributed_Database/projects/CS5424/txs/tx_workloadA.py", line 551, in related_customer_transaction
    ''', (order[0], w_id, d_id, w_id)
psycopg2.errors.SerializationFailure: restart transaction: TransactionRetryWithProtoRefreshError: ReadWithinUncertaintyIntervalError: read at time 1635679282.569042000,0 encountered previous write with future timestamp 1635679282.569042000,1 within uncertainty interval `t <= (local=1635679282.599620000,0, global=1635679283.069042000,0)`; observed timestamps: [{1 1635679282.570298000,0} {4 1635679282.569042000,0} {5 1635679282.599620000,0}]: "sql txn" meta={id=41ae8e17 pri=0.07121237 epo=0 ts=1635679282.569042000,0 min=1635679282.569042000,0 seq=0} lock=false stat=PENDING rts=1635679282.569042000,0 wto=false gul=1635679283.069042000,0
HINT:  See: https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#readwithinuncertaintyinterval

 ]
INFO:__main__:Running Tx RelCustomerTxParams successful at the 2 time retry
INFO:__main__:============================ record when total_tx_num reaches 300=====================
INFO:__main__:============================ record when total_tx_num reaches 400=====================
INFO:__main__:============================ record when total_tx_num reaches 500=====================
INFO:__main__:============================ record when total_tx_num reaches 600=====================
INFO:__main__:============================ record when total_tx_num reaches 700=====================
INFO:__main__:============================ record when total_tx_num reaches 800=====================
INFO:__main__:============================ record when total_tx_num reaches 900=====================
INFO:__main__:============================ using file /opt/project_files/xact_files_A/28.txt=====================
INFO:__main__:{'NewOrderTxParams': 283, 'DeliveryTxParams': 74, 'PaymentTxParams': 485, 'TopBalanceTxParams': 16, 'OrderStatusTxParams': 11, 'StockLevelTxParams': 20, 'PopItemTxParams': 8, 'RelCustomerTxParams': 4}
INFO:__main__:{'NewOrderTxParams': 283, 'DeliveryTxParams': 74, 'PaymentTxParams': 485, 'TopBalanceTxParams': 16, 'OrderStatusTxParams': 11, 'StockLevelTxParams': 20, 'PopItemTxParams': 8, 'RelCustomerTxParams': 4}
INFO:__main__:============================ total time used: 2658.8253989219666 second =====================
